version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=gregoriomelo.com
    restart: always

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  blog:
    build:
      context: .
      dockerfile: b
    container_name: blog
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=blog.gregoriomelo.com,gregoriomelo.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=gregorio@gregoriomelo.com
      - LETSENCRYPT_HOST=gregoriomelo.com,blog.gregoriomelo.com
    restart: always
