version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=gregoriomelo.com
    restart: always

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy

  blog:
    image: gregoriomelo/blog
    container_name: blog
    ports:
      - "80"
    volumes:
      - ./certs:/etc/nginx/certs
    environment:
      - VIRTUAL_HOST=blog.gregoriomelo.com,gregoriomelo.com
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_EMAIL=gregorio@gregoriomelo.com
      - LETSENCRYPT_HOST=gregoriomelo.com,blog.gregoriomelo.com
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:9.5.0-ce.0
    container_name: gitlab
    hostname: gitlab
    ports:
      - "80"
      - "443"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./certs:/etc/gitlab/ssl:ro
    environment:
      VIRTUAL_HOST: gitlab.gregoriomelo.com,git.gregoriomelo.com
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_EMAIL: gregorio@gregoriomelo.com
      LETSENCRYPT_HOST: gitlab.gregoriomelo.com,git.gregoriomelo.com
      GITLAB_OMNIBUS_CONFIG: |
            external_url 'https://gitlab.gregoriomelo.com'
            gitlab_shell_ssh_port 2222
    restart: always

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine-bleeding
    container_name: gitlab-runner
    hostname: gitlab-runner
    links:
      - "gitlab:gitlab.gregoriomelo.com"
    volumes:
      - ./gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

