- hosts: all

  vars:
    remote_username: "{{ lookup('env', 'REMOTE_USERNAME') }}"
    setup_from: "{{ lookup('env', 'SETUP_FROM') }}"
    setup_to: "{{ lookup('env', 'SETUP_TO') }}"
    ssh_key_path: "{{ lookup('env', 'SSH_KEY_PATH') }}"

    swapfile_location: /swapfile
    swapfile_size: 4G
    swapfile_swappiness: 10
    swapfile_vfs_cache_pressure: 50

    backup_user: "{{ remote_username }}"
    backup_directories:
      - "/home/{{ remote_username }}/gitlab"
      - "/home/{{ remote_username }}/gitlab-runner"
    backup_mysql: false

  pre_tasks:
    - name: "Check whether the right params are set"
      fail:
        msg: "Please set up the following environment variables: REMOTE_USERNAME, SETUP_FROM, SETUP_TO and SSH_KEY_PATH"
      when: (remote_username == "") or (setup_from == "") or (setup_to == "") or (ssh_key_path == "")

  roles:
    - name: geerlingguy.docker
    - name: geerlingguy.security
      security_sudoers_passwordless: ["{{ remote_username }}"]
      become: true
    - name: gregoriomelo.com
    - name: geerlingguy.backup
